config/routes.rb
Ritly::Application.routes.draw do
  root "home#index"

  resources :urls, only: [:new, :create, :show]
	resources :sessions, only: [:new, :create]
	get '/logout', to: "sessions#destroy"
  get '/:code', to: 'urls#redirector'
  get '/:code/preview', to: 'urls#preview'
end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password, presence: true
  validates :username, uniqueness: true

  def self.create_with_password(username, password)
    hash = password_hash(password)
    User.create(username: username, password: hash)
  end

  def self.find_authenticated_user(username, password)
    User.where(username:username, password: password_hash(password)).first
  end

  private
  def self.password_hash(password)
    return Digest::SHA2.hexdigest(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
    @user = User.find_authenticated_user(params[:username], params[:password])
    if @user.present?
      flash[:notice] = "Welcome back #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to urls_path
    else
      flash[:notice] = "Invalid username or password."
      redirect_to new_session_path
    end
	end

	def destroy
	end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    safe_url_params = params.require(:url).permit(:link)
    @url = Url.new safe_url_params
    @url.hash_code = rand(1..1000000)

    # For the bonus
    # @url.hash_code = SecureRandom.urlsafe_base64(8)

    @url.save

    # Or create it in one shot by merging the random parameter into the safe params hash
    # @url = Url.create safe_url_params.merge(hash_code: SecureRandom.urlsafe_base64(8))
    redirect_to @url
  end

  def show
    @url = Url.find params[:id]
    @full_path = "#{request.protocol}#{request.host_with_port}/#{@url.hash_code}"
  end

  def redirector
    @url = Url.find_by hash_code: params[:code]
    if @url
      redirect_to @url.link
    else
      redirect_to root_path
    end
  end

  def preview
    @url = Url.find_by hash_code: params[:code]
    unless @url
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/index.html.erb
<h1>Welcome to Ritly</h1>
<p><%= link_to "Click here to create a new short link", new_url_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<h1>New Ritly URL</h1>

<br/>

<%= form_for @url do |f| %>
  <b><%= f.label :link, "URL To Shorten:" %></b>
  <%= f.url_field :link %>

  <br/><br/><br/>
  <%= f.submit "Create URL" %>
<% end %>

app/views/urls/preview.html.erb
<h1>Code: <%= @url.hash_code %></h1>
<p>This code will take you to <%= @url.link %></p>
<%= link_to "Click Here", @url.link %> to continue

app/views/urls/show.html.erb
<h1><%= @url.hash_code%> is your code for <%= @url.link %></h1>

<p>You can direct users to this Ritly URL: <%= link_to @full_path %></p>

<p>The Ritly URL will redirect them to: <%= link_to @url.link, @url.link %></p>